# Generated by Django 4.2 on 2023-04-18 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=300)),
                ('user_role', models.CharField(max_length=300)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user_DP/')),
                ('social_link', models.CharField(max_length=200)),
                ('user_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserAdditionalInfo',
            },
        ),
    ]
